### ISSUE TITLE
Running test class - 'str' object is not callable

### ISSUE THREAD

**Issue by martinsvoboda** [djentlemen/django-smoked#6]
I'm trying run basic smoke test class example from readme. Runner returns `'str' object is not callable`. Is running class already implemented?

```
> python manage.py smoked -v 3
None... Fail!
'str' object is not callable

Results
=======
Total: 1
Success: 0
Failure: 1
--------
Time: 0.0s
```

``` python
# W:\citaty\citaty\smoke_tests\tests.py
from smoked.registry import SmokeTest
import smoked

class DatabaseTest(SmokeTest):
    name = 'Database test'
    description = 'Check all database connection are valid'

    def test(self):
        return True
smoked.register('citaty.smoke_tests.tests.DatabaseTest')
```

**Comment by tricoder42** [comment]
class-based tests aren't implemented yet. I wasn't sure if it's really necessary to use classes, so I implemented the first built-in smoke test as a simple function:

https://github.com/djentlemen/django-smoked/blob/master/smoked/test/url.py#L7

Moreover, lazy loading isn't implemented yet. You need to pass a callable object to `register`:

``` python
def test_function():
    return True

smoked.register(test_function)
```

`README.md` should be definitely updated, also the error message which is very confusing.

**Comment by tricoder42** [comment]
README updated in 35509a5e

**Comment by martinsvoboda** [comment]
Thanks for fixing README, we can close this issue.
